language: node_js
node_js:
  - 0.8
branches:
only:
  - master
  - active
  - have-data
before_script: PORT=8001 node server.js &
notifications:
  email:
    recipients:
      - admin@astrolet.net
    on_success: change
    on_failure: always

